onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver

patchedDependencies:
  '@nx/js@22.2.1': patches/@nx__js@22.2.1.patch
